export type AIProviderInfo = {
  label: string;
  title: string;
  tone: "local" | "offline";
};

export function getAIProviderInfo(provider: string): AIProviderInfo {
  if (provider === "ollama") {
    return {
      label: "Ollama",
      title: "Generated locally by Ollama on your machine",
      tone: "local",
    };
  }
  return {
    label: "Smart rules",
    title: "Generated by built-in offline rules (Ollama was unavailable)",
    tone: "offline",
  };
}
